GET http://localhost:3001/api/users
?limit=10
&offset=0

###

POST http://localhost:3001/api/books
content-type: application/json

{
   "author": 1,
    "title":"FlyHigh 1.1", 
    "description":"English book"
}

###

PUT http://localhost:3001/api/books/1
content-type: application/json

{
    "description":"English book - updated"
}

###

DELETE http://localhost:3001/api/books/3

###

GET http://localhost:3001/api/books
?author=1


###

POST http://localhost:3001/api/reserved-books
content-type: application/json

{
    "book_id":"2", 
    "reader":"Zorg5"
}

###

GET http://localhost:3001/api/reserved-books

###

DELETE http://localhost:3001/api/reserved-books/6

